param(
  [string]$BackendBaseUrl = "http://localhost:8080",
  [int]$Steps = 60
)

$ErrorActionPreference = "Stop"
$root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$outDir = $PSScriptRoot
$utf8 = [System.Text.UTF8Encoding]::new($false)

function Write-Utf8File([string]$Path, [string]$Content) {
  [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

Write-Host "Loading default scenario from $BackendBaseUrl ..."
$configResponse = Invoke-RestMethod -TimeoutSec 8 -Uri "$BackendBaseUrl/api/v1/experiments/default"
if (-not $configResponse.success) {
  throw "Default scenario request failed."
}

$config = $configResponse.data
$config.simulationSteps = $Steps
$body = $config | ConvertTo-Json -Depth 12

Write-Host "Running simulation with $Steps steps ..."
$runResponse = Invoke-RestMethod -TimeoutSec 15 -Method Post -Uri "$BackendBaseUrl/api/v1/simulations/run" -ContentType "application/json" -Body $body
if (-not $runResponse.success) {
  throw "Simulation request failed."
}

$simulation = $runResponse.data
$detail = $null
try {
  $detailResponse = Invoke-RestMethod -TimeoutSec 8 -Uri "$BackendBaseUrl/api/v1/simulations/$($simulation.runId)/detail"
  if ($detailResponse.success) {
    $detail = $detailResponse.data
  }
} catch {
  Write-Host "Detail endpoint was not available; using run snapshot only."
}

$payload = [ordered]@{
  generatedAt = (Get-Date).ToString("s")
  backendBaseUrl = $BackendBaseUrl
  simulation = $simulation
  detail = $detail
}

$json = $payload | ConvertTo-Json -Depth 40
$jsonPath = Join-Path $outDir "latest-simulation.json"
Write-Utf8File $jsonPath $json

$metrics = $simulation.metrics
$report = @"
# FusionPilot Demo Simulation Report

Generated at: $($payload.generatedAt)

## Run Summary

- Run ID: $($simulation.runId)
- Scenario: $($simulation.config.scenarioName)
- Targets: $($simulation.config.targetCount)
- Steps: $($simulation.config.simulationSteps)
- Scheduling policy: $($simulation.config.schedulingPolicy)
- Fusion method: $($simulation.config.fusionMethod)
- Random seed: $($simulation.config.randomSeed)

## Aggregate Metrics

- Average position error: $([Math]::Round($metrics.averagePositionError, 4))
- Tracking rate: $([Math]::Round($metrics.trackingRate * 100, 2))%
- Resource utilization: $([Math]::Round($metrics.resourceUtilization * 100, 2))%
- Average waiting time: $([Math]::Round($metrics.averageWaitingTime, 4))
- Scheduling switches: $($metrics.schedulingSwitches)

## Data Provenance

This report is generated from the Java Spring Boot simulation API:

- GET /api/v1/experiments/default
- POST /api/v1/simulations/run
- GET /api/v1/simulations/{runId}/detail when available

The trajectory data is synthetic and generated by the Java backend from the default multi-target scenario. It is not hand-entered data and is not an external dataset.
"@

$reportPath = Join-Path $outDir "simulation-report.md"
Write-Utf8File $reportPath $report

$escapedJson = $json.Replace("</script>", "<\/script>")
$html = @"
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>FusionPilot Simulation Viewer</title>
  <style>
    :root {
      color-scheme: dark;
      font-family: Inter, "Microsoft YaHei", Arial, sans-serif;
      background: #07111f;
      color: #e5eefb;
    }
    body { margin: 0; background: #07111f; }
    .shell { max-width: 1180px; margin: 0 auto; padding: 24px; }
    header { display: flex; justify-content: space-between; gap: 18px; align-items: flex-start; margin-bottom: 18px; }
    h1 { margin: 0 0 8px; font-size: 28px; }
    p { margin: 0; color: #91a7c4; }
    .grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 10px; margin: 18px 0; }
    .card, .panel { border: 1px solid #274160; background: #0c192b; border-radius: 6px; padding: 14px; }
    .card span { display: block; color: #87a0bd; font-size: 12px; margin-bottom: 8px; }
    .card strong { font-size: 20px; color: #38bdf8; }
    .panel { margin-top: 14px; }
    canvas { width: 100%; height: 520px; display: block; background: #081525; border: 1px solid #203852; border-radius: 6px; }
    .controls { display: flex; align-items: center; gap: 12px; margin: 14px 0; }
    input[type="range"] { flex: 1; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; color: #cfe0f5; }
    th, td { border-bottom: 1px solid #203852; padding: 8px; text-align: left; }
    th { color: #78a7d8; font-weight: 600; }
    .tag { color: #38bdf8; border: 1px solid #2e5b7c; padding: 6px 9px; border-radius: 4px; }
    @media (max-width: 860px) { .grid { grid-template-columns: 1fr 1fr; } header { flex-direction: column; } }
  </style>
</head>
<body>
  <div class="shell">
    <header>
      <div>
        <h1>FusionPilot Simulation Viewer</h1>
        <p id="subtitle"></p>
      </div>
      <div class="tag" id="runId"></div>
    </header>
    <section class="grid" id="metrics"></section>
    <section class="panel">
      <h2>Truth Trajectory and Fused Estimate</h2>
      <canvas id="track" width="1100" height="520"></canvas>
      <div class="controls">
        <span>Time step</span>
        <input id="step" type="range" min="0" value="0" />
        <strong id="stepLabel"></strong>
      </div>
    </section>
    <section class="panel">
      <h2>Current Resource Assignment</h2>
      <table>
        <thead><tr><th>Target</th><th>Allocated</th><th>Priority Score</th><th>Reason</th></tr></thead>
        <tbody id="assignments"></tbody>
      </table>
    </section>
  </div>
  <script>
    const payload = $escapedJson;
    const simulation = payload.simulation;
    const canvas = document.getElementById('track');
    const ctx = canvas.getContext('2d');
    const stepInput = document.getElementById('step');
    const colors = ['#38bdf8', '#a78bfa', '#fbbf24', '#34d399', '#fb7185'];
    document.getElementById('runId').textContent = 'Run ' + simulation.runId.slice(0, 8);
    document.getElementById('subtitle').textContent = simulation.config.scenarioName + ' / ' + simulation.config.schedulingPolicy + ' / seed ' + simulation.config.randomSeed;
    const metricItems = [
      ['Position Error', simulation.metrics.averagePositionError.toFixed(3)],
      ['Tracking Rate', (simulation.metrics.trackingRate * 100).toFixed(1) + '%'],
      ['Resource Utilization', (simulation.metrics.resourceUtilization * 100).toFixed(1) + '%'],
      ['Average Waiting', simulation.metrics.averageWaitingTime.toFixed(3)],
      ['Switch Count', simulation.metrics.schedulingSwitches]
    ];
    document.getElementById('metrics').innerHTML = metricItems.map(([name, value]) => '<div class="card"><span>' + name + '</span><strong>' + value + '</strong></div>').join('');
    stepInput.max = Math.max(0, simulation.steps.length - 1);

    function allPoints() {
      const points = [];
      for (const step of simulation.steps) {
        for (const item of step.trueStates) points.push([item.x, item.y]);
        for (const item of step.fusedStates) points.push([item.x, item.y]);
      }
      return points;
    }
    const points = allPoints();
    const xs = points.map(p => p[0]);
    const ys = points.map(p => p[1]);
    const minX = Math.min(...xs), maxX = Math.max(...xs), minY = Math.min(...ys), maxY = Math.max(...ys);
    function sx(x) { return 46 + (x - minX) / Math.max(1, maxX - minX) * (canvas.width - 86); }
    function sy(y) { return canvas.height - 42 - (y - minY) / Math.max(1, maxY - minY) * (canvas.height - 82); }
    function line(points, color, dash) {
      ctx.save();
      ctx.strokeStyle = color;
      ctx.lineWidth = 2;
      if (dash) ctx.setLineDash([8, 7]);
      ctx.beginPath();
      points.forEach((p, i) => { const x = sx(p[0]), y = sy(p[1]); i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); });
      ctx.stroke();
      ctx.restore();
    }
    function dot(x, y, color, radius) {
      ctx.fillStyle = color;
      ctx.beginPath();
      ctx.arc(sx(x), sy(y), radius, 0, Math.PI * 2);
      ctx.fill();
    }
    function draw(index) {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.fillStyle = '#081525';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.strokeStyle = '#1f344d';
      ctx.lineWidth = 1;
      for (let i = 0; i < 8; i++) {
        const x = 46 + i * (canvas.width - 86) / 7;
        const y = 32 + i * (canvas.height - 82) / 7;
        ctx.beginPath(); ctx.moveTo(x, 32); ctx.lineTo(x, canvas.height - 42); ctx.stroke();
        ctx.beginPath(); ctx.moveTo(46, y); ctx.lineTo(canvas.width - 40, y); ctx.stroke();
      }
      const targetCount = simulation.config.targetCount;
      for (let targetId = 1; targetId <= targetCount; targetId++) {
        const truth = simulation.steps.slice(0, index + 1).map(step => step.trueStates.find(s => s.targetId === targetId)).filter(Boolean).map(s => [s.x, s.y]);
        const fused = simulation.steps.slice(0, index + 1).map(step => step.fusedStates.find(s => s.targetId === targetId)).filter(Boolean).map(s => [s.x, s.y]);
        const color = colors[(targetId - 1) % colors.length];
        line(truth, color, false);
        line(fused, color, true);
        const lastTruth = truth[truth.length - 1];
        const lastFused = fused[fused.length - 1];
        if (lastTruth) dot(lastTruth[0], lastTruth[1], color, 5);
        if (lastFused) dot(lastFused[0], lastFused[1], '#ffffff', 3);
      }
      const step = simulation.steps[index];
      document.getElementById('stepLabel').textContent = (index + 1) + ' / ' + simulation.steps.length;
      document.getElementById('assignments').innerHTML = step.scheduling.assignments.map(item => '<tr><td>T' + item.targetId + '</td><td>' + (item.allocated ? 'Allocated' : 'Waiting') + '</td><td>' + item.priorityScore.toFixed(3) + '</td><td>' + item.reason + '</td></tr>').join('');
    }
    stepInput.addEventListener('input', () => draw(Number(stepInput.value)));
    draw(0);
  </script>
</body>
</html>
"@

$htmlPath = Join-Path $outDir "simulation-viewer.html"
Write-Utf8File $htmlPath $html

Write-Host "Generated:"
Write-Host "  $jsonPath"
Write-Host "  $reportPath"
Write-Host "  $htmlPath"
